/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    pages: Page;
    media: Media;
    'keyword-clusters': KeywordCluster;
    'generation-batches': GenerationBatch;
    domains: Domain;
    niches: Niche;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'keyword-clusters': KeywordClustersSelect<false> | KeywordClustersSelect<true>;
    'generation-batches': GenerationBatchesSelect<false> | GenerationBatchesSelect<true>;
    domains: DomainsSelect<false> | DomainsSelect<true>;
    niches: NichesSelect<false> | NichesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The article headline (H1), in the domain's language
   */
  title: string;
  /**
   * Every post belongs to exactly one domain; it is never shared across domains
   */
  domain: number | Domain;
  /**
   * The keyword cluster this post was generated from
   */
  sourceCluster?: (number | null) | KeywordCluster;
  template: 'listicle' | 'informational';
  /**
   * URL segment, unique within the domain
   */
  slug: string;
  status: 'draft' | 'scheduled' | 'published' | 'failed';
  scheduledAt?: string | null;
  publishedAt?: string | null;
  featuredImage?: (number | null) | Media;
  intro?: string | null;
  /**
   * Listicle template only
   */
  products?:
    | {
        title: string;
        description?: string | null;
        /**
         * Pulled from the affiliate product feed
         */
        imageUrl?: string | null;
        /**
         * Link for this domain's country marketplace, e.g. amazon.com
         */
        affiliateUrl: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Informational template only
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  summary?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains".
 */
export interface Domain {
  id: number;
  name: string;
  /**
   * The domain this site is served from, e.g. example.com
   */
  hostname: string;
  /**
   * The topic area this domain covers. Content runs are grouped by niche.
   */
  niche: number | Niche;
  /**
   * The single language + country this domain publishes in. One of: en-US, da-DK
   */
  locale: string;
  /**
   * Where this domain's listicle products come from — the affiliate marketplace for its country
   */
  affiliate: {
    /**
     * Product source implementation: `mock`, or the affiliate network name
     */
    source: string;
    /**
     * Marketplace for this country, e.g. amazon.com or amazon.de
     */
    marketplace?: string | null;
    /**
     * Affiliate partner/tracking tag added to every product link
     */
    partnerTag?: string | null;
  };
  branding?: {
    logo?: (number | null) | Media;
    primaryColor?: string | null;
    accentColor?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "niches".
 */
export interface Niche {
  id: number;
  /**
   * Display name, e.g. Outdoor
   */
  name: string;
  /**
   * Short identifier used in scripts and filters, e.g. outdoor
   */
  slug: string;
  /**
   * What this niche covers, for editors
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keyword-clusters".
 */
export interface KeywordCluster {
  id: number;
  /**
   * Where the keywords came from: DataForSEO research (phase 05) or entered by hand
   */
  source: 'dataforseo' | 'manual';
  clusterName: string;
  keywords: {
    keyword: string;
    searchVolume?: number | null;
    id?: string | null;
  }[];
  targetDomain: number | Domain;
  targetTemplate: 'listicle' | 'informational';
  status: 'unused' | 'assigned' | 'used';
  /**
   * The article generated from this cluster, once created
   */
  post?: (number | null) | Post;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  domain: number | Domain;
  type: 'about' | 'privacy' | 'imprint' | 'terms' | 'affiliate-disclosure' | 'contact' | 'other';
  /**
   * URL segment, unique within the domain across pages and posts
   */
  slug: string;
  status: 'draft' | 'published';
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generation-batches".
 */
export interface GenerationBatch {
  id: number;
  anthropicBatchId: string;
  /**
   * Every cluster in a batch targets this domain
   */
  domain: number | Domain;
  /**
   * Schedule the imported posts automatically once they are ready (phase 06)
   */
  autoSchedule?: boolean | null;
  status: 'submitted' | 'in_progress' | 'ended' | 'importing' | 'imported' | 'failed';
  requests?:
    | {
        customId: string;
        cluster: number | KeywordCluster;
        post?: (number | null) | Post;
        importState: 'pending' | 'imported' | 'errored';
        error?: string | null;
        inputTokens?: number | null;
        outputTokens?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The product list per cluster (keyed by custom ID) that the model saw
   */
  productSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  submittedAt?: string | null;
  endedAt?: string | null;
  importedAt?: string | null;
  requestCounts?: {
    processing?: number | null;
    succeeded?: number | null;
    errored?: number | null;
    canceled?: number | null;
    expired?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'keyword-clusters';
        value: number | KeywordCluster;
      } | null)
    | ({
        relationTo: 'generation-batches';
        value: number | GenerationBatch;
      } | null)
    | ({
        relationTo: 'domains';
        value: number | Domain;
      } | null)
    | ({
        relationTo: 'niches';
        value: number | Niche;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  domain?: T;
  sourceCluster?: T;
  template?: T;
  slug?: T;
  status?: T;
  scheduledAt?: T;
  publishedAt?: T;
  featuredImage?: T;
  intro?: T;
  products?:
    | T
    | {
        title?: T;
        description?: T;
        imageUrl?: T;
        affiliateUrl?: T;
        id?: T;
      };
  body?: T;
  summary?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  domain?: T;
  type?: T;
  slug?: T;
  status?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keyword-clusters_select".
 */
export interface KeywordClustersSelect<T extends boolean = true> {
  source?: T;
  clusterName?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        searchVolume?: T;
        id?: T;
      };
  targetDomain?: T;
  targetTemplate?: T;
  status?: T;
  post?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "generation-batches_select".
 */
export interface GenerationBatchesSelect<T extends boolean = true> {
  anthropicBatchId?: T;
  domain?: T;
  autoSchedule?: T;
  status?: T;
  requests?:
    | T
    | {
        customId?: T;
        cluster?: T;
        post?: T;
        importState?: T;
        error?: T;
        inputTokens?: T;
        outputTokens?: T;
        id?: T;
      };
  productSnapshot?: T;
  submittedAt?: T;
  endedAt?: T;
  importedAt?: T;
  requestCounts?:
    | T
    | {
        processing?: T;
        succeeded?: T;
        errored?: T;
        canceled?: T;
        expired?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains_select".
 */
export interface DomainsSelect<T extends boolean = true> {
  name?: T;
  hostname?: T;
  niche?: T;
  locale?: T;
  affiliate?:
    | T
    | {
        source?: T;
        marketplace?: T;
        partnerTag?: T;
      };
  branding?:
    | T
    | {
        logo?: T;
        primaryColor?: T;
        accentColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "niches_select".
 */
export interface NichesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}